name: AzOps-Push

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to trigger (pull or push)"
        required: true
        default: "push"
  pull_request:
    branches:
      - "main"
    paths:
      - "azops/**"
  pull_request_review:
    branches:
      - "main"
    types:
      - "submitted"
    paths:
      - "azops/**"

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZOPS_STATE: "azops"
  AZOPS_DEFAULT_DEPLOYMENT_REGION: "northeurope"
  AZOPS_ENROLLMENT_ACCOUNT: ""
  AZOPS_OFFER_TYPE: "MS-AZR-0017P"
  AZOPS_IGNORE_CONTEXT_CHECK: "0"
  AZOPS_INVALIDATE_CACHE: "1"
  AZOPS_SKIP_RESOURCE_GROUP: "1"
  AZOPS_SKIP_POLICY: "0"
  AZOPS_THROTTLE_LIMIT: "10"
  GITHUB_USERNAME: "AzOps"
  GITHUB_EMAIL: "noreply@azure.com"
  GITHUB_PULL_REQUEST: "Azure Change Notification"
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_ISSUE: ${{ github.event.pull_request._links.issue.href }}
  GITHUB_COMMENTS: ${{ github.event.pull_request._links.comments.href }}
  GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
  GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCM_PLATFORM: "GitHub"
  VERBOSE: "0"
  DEBUG: "0"

jobs:
  push:
    timeout-minutes: 120
    if: github.head_ref != 'system' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'push'
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: GitHub context
        run: echo "$GITHUB_CONTEXT"
      - name: Actions azops
        uses: Azure/AzOps@main
        with:
          mode: push
  # If you want review before triggering the push event, enable 'push_review' uncomment block below and comment 'push' block
  # Review will require, someone other than the creator of the pull request to complete review.
  # Workflow will run once pull request is reviewed with a comment that contains "LGTM".
  # In order for GitHub Actions status check to display in your PR, you have to enable branch access policy.
  #
  #
  # push_review:
  #   timeout-minutes: 120
  #   if: github.head_ref != 'system' && contains(github.event.review.body, 'LGTM')
  #   name: Push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Actions checkout
  #       uses: actions/checkout@v2
  #     - name: GitHub context
  #       run: echo "$GITHUB_CONTEXT"
  #     - name: Actions azops
  #       uses: Azure/AzOps@main
  #       with:
  #         mode: push
