---
    name: Check Policy Build
    
    ##########################################
    # Start the job on PR for all branches #
    ##########################################
    
    # yamllint disable-line rule:truthy
    on:
      pull_request:
        types:
          - opened
          - reopened
          - synchronize
          - ready_for_review
        paths:
          - "eslzArm/**.json"
          - "src/Alz.Tools/**"
          - "src/**.json"
          - "src/**.bicep"
    
    env:
      github_user_name: "github-actions"
      github_email: "41898282+github-actions[bot]@users.noreply.github.com"
      github_pr_number: ${{ github.event.number }}
    
    permissions:
      contents: write
    
    ###############
    # Set the Job #
    ###############
    
    jobs:
      check-policy:
        name: Check Policy Build
        runs-on: ubuntu-latest

        steps:
          - name: Check out repository
            uses: actions/checkout@v4
    
          - name: Show env
            run: env | sort
    
          - name: Check out PR
            run: |
              echo "==> Check out PR..."
              gh pr checkout "$github_pr_number"
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
          # - name: Configure local git
          #   run: |
          #     echo "git user name  : $github_user_name"
          #     git config --global user.name "$github_user_name"
          #     echo "git user email : $github_email"
          #     git config --global user.email "$github_email"

          - name: Check build
            shell: pwsh
            run: |
              Import-Module Pester -Force
                $pesterConfiguration = @{
                  Run    = @{
                    Container = New-PesterContainer -Path "./.github/actions-pester/Test-BuildPolicies.Tests.ps1"
                    PassThru  = $true
                  }
                  Output = @{
                    Verbosity = 'Detailed'
                  }
                }
                $result = Invoke-Pester -Configuration $pesterConfiguration
                exit $result.FailedCount