name: Functional Test for Policies
on:
    pull_request_target:
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
      paths:
        - "src/**.json"
        - "src/**.bicep"
    workflow_dispatch:
      inputs:
        remarks:
          description: "Reason for triggering the workflow run"
          required: false
          default: "Testing Azure Policies..."
jobs:
  test-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            ref: ${{github.event.pull_request.head.ref}}
            repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Test Azure Policies
        shell: pwsh
        run: |
          Invoke-Pester -Output Detailed -CI -Path "./tests/policy/*.tests.ps1"
